SELECT 'MCC' AS nom_table, COUNT(*) AS nb_lignes FROM mcc UNION ALL
SELECT 'CLIENT', COUNT(*) FROM client UNION ALL
SELECT 'CARTE', COUNT(*) FROM carte UNION ALL
SELECT 'MARCHAND', COUNT(*) FROM marchand UNION ALL
SELECT 'TRANSACTION', COUNT(*) FROM transaction UNION ALL
SELECT 'LABEL_FRAUDE', COUNT(*) FROM label_fraude UNION ALL
SELECT 'ERREUR_TRANSACTION', COUNT(*) FROM erreur_transaction UNION ALL
SELECT 'UTILISATEUR_SI', COUNT(*) FROM utilisateur_si UNION ALL
SELECT 'JOURNAL_AUDIT', COUNT(*) FROM journal_audit
ORDER BY 1;
