EXPLAIN PLAN FOR
SELECT t.id_carte, COUNT(*) AS nb_tx, SUM(t.amount) AS total
FROM transaction t
WHERE t.situation_date BETWEEN TRUNC(SYSDATE, 'MM') AND LAST_DAY(SYSDATE)
GROUP BY t.id_carte
ORDER BY nb_tx DESC
FETCH FIRST 10 ROWS ONLY;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY(format => 'BASIC +PARTITION +PREDICATE'));
